

FROM python:3.10

RUN pip install --upgrade pip
RUN pip install pipenv

COPY ./Pipfile ./Pipfile.lock /app/
WORKDIR /app
RUN pipenv install --dev

COPY . /app/

EXPOSE 8000
CMD ["uvicorn", "main:app", "--reload", "--port", "8000"]

# RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# COPY ./app /code/app

# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]