
FROM node:18-alpine

RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app
COPY . .
# COPY ../docker/dev/frontend-start.sh .

RUN yarn install
RUN yarn run build

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

EXPOSE 3000 3001

CMD ./frontend-start.sh