

FROM python:3.10

RUN pip install --upgrade pip
RUN pip install pipenv

COPY ./Pipfile ./Pipfile.lock /app/
WORKDIR /app
RUN pipenv install --dev

COPY . /app/

EXPOSE 8000
CMD ["uvicorn", "main:app", "--reload", "--port", "8000"]